server:
  port: 9091
spring:
  application:
    name: consume-nacos-service #注册到注册中心的名字 消费者
  cloud:
    nacos:
      discovery:
        server-addr:  localhost:8848 #nacos的ip地址
#     配置 Sentinel
    sentinel:
      transport:
        dashboard: localhost:8849
        #默认8719端口，假如被占用会自动从8719开始依次扫描，直至找到未被占用的端口
        port: 8720
        clientIp: localhost
      eager: true  #取消控制台懒加载，默认false要刷新请求sentinel才会在面板显示

feign:
  client:
    config:
#      配置fegin超时
      default:
        connectTimeout: 10000
        readTimeout: 10000
  sentinel:
    enabled: true
