# windows配置
server:
  port: 8081
spring:
  application:
    name: provide-nacos-service #注册到注册中心的名字  提供者
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #nacos的ip地址
        enabled: true
  datasource:
#    type: org.apache.commons.dbcp2.BasicDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.135.54.170:3306/boran_glerp?characterEncoding=utf-8
    username: boran_glerp
    password: FpYb76fZ4czpiLnr
    hikari:
      minimum-idle: 10
    dbcp2: #启用dbcp2配置
      min-idle: 5 #最小空闲连接:连接池中容许保持空闲状态的最小连接数量,
      initial-size: 5 #初始化连接数量
      max-total: 10
      max-wait-millis: 200
    platform: mysql
  mvc:
    servlet:
      load-on-startup: 1
  servlet:
    multipart:
      max-file-size: 512MB
      max-request-size: 512MB
      enabled: true
#      redis配置
  redis:
    database: 1  # Redis数据库索引(默认为0)
    host: 8.135.54.170 # Redis服务器地址
    port: 6379  # Redis服务器连接端口
    password: boran123  # Redis服务器连接密码(默认为空)
    # 连接超时时间（毫秒）
    timeout: 0
    jedis:
      pool:
        # 连接池最大连接数 连接池最大连接数(使用负值表示没有限制) 默认 8
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 连接池最大阻塞等待时间(使用负值表示没有限制) 默认 -1
        max-wait: -1
        # 连接池中的最大空闲连接 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池中的最小空闲连接 连接池中的最小空闲连接 默认 0
        min-idle: 2
        time-between-eviction-runs: 1000
  # sa-token配
sa-token:
  # 写入Cookie时显式指定的作用域, 用于单点登录二级域名共享Cookie
  cookie-domain: lt.com
  # token名称 (同时也是cookie名称)
  token-name: satoken
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 800
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: 180
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: false
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: false
  #token前缀
  token-prefix: BoRan

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml  #mybatis指定数据库xml文件
  typeAliasesPackage: com.example.boranqichacha.Entity      #指定实体类
  configuration:
    map-underscore-to-camel-case: false  #关闭驼峰，实体类的 *_*映射
    auto-mapping-behavior: full
    use-generated-keys: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 0
      logic-not-delete-value: 1

logging:
  config: classpath:logback-spring.xml
  level:
    org:
      mybatis: debug
#接口文档
knife4j:
  enable: true
  documents:
    -
      group: 2.X版本
      name: 接口签名
      locations: classpath:sign/*
  setting:
    language: zh-CN
    enableSwaggerModels: true
    enableDocumentManage: true
    swaggerModelName: com.boran.erp.Entity
    enableVersion: false
    enableReloadCacheParameter: false
    enableAfterScript: true
    enableFilterMultipartApiMethodType: POST
    enableFilterMultipartApis: false
    enableRequestCache: true
    enableHost: false
    enableHostText: localhost:8002
    enableHomeCustom: true
    homeCustomLocation: classpath:markdown/home.md
    enableSearch: false
    enableFooter: false
    enableFooterCustom: true
    footerCustomContent: Apache License 2.0 | Copyright  2021-[深圳市博冉创新科技有限公司]
    enableDynamicParameter: false
    enableDebug: true
    enableOpenApi: false
    enableGroup: true
  cors: false
  production: false
  basic:
    enable: false
    username: boran
    password: boran123


# 异步线程配置
# 配置核心线程数
async:
  executor:
    thread:
      core_pool_size: 5
      max_pool_size: 5
      queue_capacity: 5
      name:
        prefix: async-service-
#      自定义注释测试
person:
  lastName: hello
  age: 18
  boss: false
  birth: 2021/4/12
  maps: {k1: v1,k2: 12}
  lists:
    ‐ lisi
    ‐ zhaoliu

seata:
  tx-service-group: provide-nacos-service
#  config:
#    type: nacos
#    nacos:
#      server-addr: 127.0.0.1:8848
#      group : "SEATA_GROUP"
#      namespace: "public"
#      username: "nacos"
#      password: "nacos"

